import { Side } from "../types/gameEnums";
import { Card } from "../types/gameTypes";

export const Cards: Card[] = [
  // Thanos cards
  {
    id: 1,
    name: "card.thanos",
    side: "THANOS",
    ability: "CANNOT_BE_PLAYED",
    numberOf: 1,
    power: 7,
  },
  {
    id: 2,
    name: "card.mindStone",
    side: "THANOS",
    ability: "GUESS_ALL_OPPONENTS_HANDS",
    numberOf: 3,
    stone: true,
    power: 1,
  },
  {
    id: 3,
    name: "card.soulStone",
    side: "THANOS",
    ability: "DEFEAT_3_HIGHER",
    numberOf: 2,
    stone: true,
    power: 2,
  },
  {
    id: 4,
    name: "card.spaceStone",
    side: "THANOS",
    ability: "MAY_FIGHT_2_OPPONENT",
    numberOf: 2,
    stone: true,
    power: 3,
  },
  {
    id: 5,
    name: "card.powerStone",
    side: "THANOS",
    ability: "TAKE_3_POWER_TOKEN",
    numberOf: 2,
    power: 4,
  },
  {
    id: 6,
    name: "card.realityStone",
    side: "THANOS",
    ability: "DRAW_2_2_CARD_ON_BOTTOM",
    numberOf: 2,
    power: 5,
  },
  {
    id: 7,
    name: "card.timeStone",
    side: "THANOS",
    ability: "COPY_A_CARD_EFFECT",
    numberOf: 2,
    power: 6,
  },
  {
    id: 8,
    name: "card.outrider",
    side: "THANOS",
    ability: "GUESS_1_OPPONENTS_HAND",
    numberOf: 2,
    power: 1,
  },
  {
    id: 9,
    name: "card.outrider",
    side: "THANOS",
    ability: "GUESS_1_OPPONENTS_HAND",
    numberOf: 3,
    power: 1,
  },
  {
    id: 10,
    name: "card.corvusGlaive",
    side: "THANOS",
    ability: "DEFEAT_3_LOWER",
    numberOf: 2,
    power: 2,
  },
  {
    id: 10,
    name: "card.blackDwarf",
    side: "THANOS",
    ability: "MAY_FIGHT_1_OPPONENT",
    numberOf: 2,
    power: 3,
  },
  {
    id: 11,
    name: "card.proximaMidnight",
    side: "THANOS",
    ability: "TAKE_1_POWER_TOKEN",
    numberOf: 2,
    power: 4,
  },
  {
    id: 12,
    name: "card.ebonyMaw",
    side: "THANOS",
    ability: "DRAW_1_1_CARD_ON_BOTTOM",
    numberOf: 2,
    power: 5,
  },

  // Heroes cards
  {
    id: 13,
    name: "card.nebula",
    side: "HEROES",
    ability: "GUESS_THANOS_HAND",
    numberOf: 3,
    power: 1,
  },
  {
    id: 14,
    name: "card.spiderMan",
    side: "HEROES",
    ability: "GUESS_THANOS_HAND",
    numberOf: 3,
    power: 1,
  },
  {
    id: 15,
    name: "card.starLord",
    side: "HEROES",
    ability: "GUESS_THANOS_HAND",
    numberOf: 3,
    power: 1,
  },
  {
    id: 16,
    name: "card.blackWidow",
    side: "HEROES",
    ability: "TEAMMATE_SEES_CARD",
    numberOf: 3,
    power: 2,
  },
  {
    id: 17,
    name: "card.gamora",
    side: "HEROES",
    ability: "TEAMMATE_SEES_CARD",
    numberOf: 3,
    power: 2,
  },
  {
    id: 18,

    name: "card.antManWasp",
    side: "HEROES",
    ability: "TEAMMATE_SEES_CARD",
    numberOf: 3,
    power: 2,
  },
  {
    id: 19,
    name: "card.captainAmerica",
    side: "HEROES",
    ability: "MAY_FIGHT_THANOS",
    numberOf: 3,
    power: 3,
  },
  {
    id: 20,
    name: "card.hulk",
    side: "HEROES",
    ability: "MAY_FIGHT_THANOS",
    numberOf: 3,
    power: 3,
  },
  {
    id: 21,
    name: "card.thor",
    side: "HEROES",
    ability: "MAY_FIGHT_THANOS",
    numberOf: 3,
    power: 3,
  },
  {
    id: 22,
    name: "card.blackPanther",
    side: "HEROES",
    ability: "GIVE_1_POWER_TOKEN",
    numberOf: 3,
    power: 4,
  },
  {
    id: 23,
    name: "card.falcon",
    side: "HEROES",
    ability: "GIVE_1_POWER_TOKEN",
    numberOf: 3,
    power: 4,
  },
  {
    id: 24,
    name: "card.doctorStrange",
    side: "HEROES",
    ability: "GIVE_1_POWER_TOKEN",
    numberOf: 3,
    power: 4,
  },
  {
    id: 25,
    name: "card.scarletWitch",
    side: "HEROES",
    ability: "REARRANGE_TOP_3_CARDS",
    numberOf: 2,
    power: 5,
  },
  {
    id: 26,
    name: "card.vision",
    side: "HEROES",

    ability: "REARRANGE_TOP_3_CARDS",
    numberOf: 2,
    power: 5,
  },
  {
    id: 27,
    name: "card.captainMarvel",
    side: "HEROES",
    ability: "YOU_OR_TEAMMATE_MAY_FIGHT",
    numberOf: 2,
    power: 6,
  },
  {
    id: 28,
    name: "card.ironMan",
    side: "HEROES",
    ability: "YOU_OR_TEAMMATE_MAY_FIGHT",
    numberOf: 2,
    power: 6,
  },
];
