export enum Side {
  THANOS = "THANOS",
  HEROES = "HEROES",
}

export enum ThanosAbilities {
  GUESS_1_OPPONENTS_HAND = "GUESS_1_OPPONENTS_HAND",
  GUESS_ALL_OPPONENTS_HANDS = "GUESS_ALL_OPPONENTS_HANDS",
  DEFEAT_3_LOWER = "DEFEAT_3_LOWER",
  DEFEAT_3_HIGHER = "DEFEAT_3_HIGHER",
  MAY_FIGHT_1_OPPONENT = "MAY_FIGHT_1_OPPONENT",
  MAY_FIGHT_2_OPPONENT = "MAY_FIGHT_2_OPPONENT",
  TAKE_1_POWER_TOKEN = "TAKE_1_POWER_TOKEN",
  TAKE_3_POWER_TOKEN = "TAKE_3_POWER_TOKEN",
  DRAW_1_1_CARD_ON_BOTTOM = "DRAW_1_1_CARD_ON_BOTTOM",
  DRAW_2_2_CARD_ON_BOTTOM = "DRAW_2_2_CARD_ON_BOTTOM",
  COPY_A_CARD_EFFECT = "COPY_A_CARD_EFFECT",
  CANNOT_BE_PLAYED = "CANNOT_BE_PLAYED",
}

export enum HeroesAbilities {
  GUESS_THANOS_HAND = "GUESS_THANOS_HAND",
  TEAMMATE_SEES_CARD = "TEAMMATE_SEES_CARD",
  MAY_FIGHT_THANOS = "MAY_FIGHT_THANOS",
  GIVE_1_POWER_TOKEN = "GIVE_1_POWER_TOKEN",
  REARRANGE_TOP_3_CARDS = "REARRANGE_TOP_3_CARDS",
  YOU_OR_TEAMMATE_MAY_FIGHT = "YOU_OR_TEAMMATE_MAY_FIGHT",
}

export enum GameStates {
  LOBBY = "LOBBY",
  PLAY = "PLAY",
  VICTORY = "VICTORY",
}

export enum PlayStates {
  DRAW_CARD = "DRAW_CARD",
  CHOOSE_ABILITY = "CHOOSE_ABILITY",
  PLAYER_TURN = "PLAYER_TURN",

  //
  SHUFFLE_DECK = "SHFFLE_DECK",

  //
  TEST_THANOS_WIN = "TEST_THANOS_WIN",
}
